/**
 * Standardized Error Response Utilities
 * Implements RFC 9457 Problem Details for HTTP APIs
 *
 * @see https://datatracker.ietf.org/doc/html/rfc9457
 *
 * `type` URIs are namespaced under a `baseUri` the host app provides (e.g.
 * `https://api.thepia.com/problems`) rather than hardcoded here, since a
 * shared library shouldn't bake one consumer's identifier namespace into
 * every other consumer's error responses.
 */

export interface ProblemDetails {
  /** A URI reference that identifies the problem type */
  type: string;
  /** A short, human-readable summary of the problem type */
  title: string;
  /** The HTTP status code generated by the origin server */
  status: number;
  /** A human-readable explanation specific to this occurrence */
  detail: string;
  /** A URI reference that identifies the specific occurrence */
  instance: string;
  /** Optional trace ID for debugging */
  traceId?: string;
  /** Optional timestamp */
  timestamp?: string;
}

export interface ValidationError extends ProblemDetails {
  /** Array of field-specific validation errors */
  errors: Array<{
    field: string;
    message: string;
    code: string;
  }>;
}

/**
 * Create a standardized RFC 9457 problem details response
 */
export function createProblemResponse(
  problem: Omit<ProblemDetails, 'timestamp'>,
  headers: Record<string, string> = {}
): Response {
  const problemDetails: ProblemDetails = {
    ...problem,
    timestamp: new Date().toISOString(),
    traceId: crypto.randomUUID()
  };

  return new Response(JSON.stringify(problemDetails), {
    status: problem.status,
    headers: {
      'Content-Type': 'application/problem+json',
      ...headers
    }
  });
}

/**
 * Create validation error response with field-level details
 */
export function createValidationErrorResponse(
  baseUri: string,
  detail: string,
  errors: ValidationError['errors'],
  instance: string
): Response {
  const problemDetails: ValidationError = {
    type: `${baseUri}/validation-error`,
    title: 'Validation Failed',
    status: 400,
    detail,
    instance,
    errors,
    timestamp: new Date().toISOString(),
    traceId: crypto.randomUUID()
  };

  return new Response(JSON.stringify(problemDetails), {
    status: 400,
    headers: {
      'Content-Type': 'application/problem+json'
    }
  });
}

/**
 * Standard error types for common API problems, namespaced under `baseUri`
 * (e.g. `https://api.thepia.com/problems` -> `${baseUri}/validation-error`).
 */
export function createErrorTypes(baseUri: string) {
  return {
    // Client errors (4xx)
    VALIDATION_ERROR: `${baseUri}/validation-error`,
    EMAIL_REQUIRED: `${baseUri}/email-required`,
    INVALID_EMAIL: `${baseUri}/invalid-email`,
    USER_NOT_FOUND: `${baseUri}/user-not-found`,
    UNAUTHORIZED: `${baseUri}/unauthorized`,
    FORBIDDEN: `${baseUri}/forbidden`,
    RESOURCE_NOT_FOUND: `${baseUri}/resource-not-found`,
    CHALLENGE_NOT_FOUND: `${baseUri}/challenge-not-found`,
    INVALID_CREDENTIALS: `${baseUri}/invalid-credentials`,

    // Server errors (5xx)
    INTERNAL_SERVER_ERROR: `${baseUri}/internal-server-error`,
    SERVICE_UNAVAILABLE: `${baseUri}/service-unavailable`,
    AUTH_SERVICE_ERROR: `${baseUri}/auth-service-error`,
    EXTERNAL_SERVICE_ERROR: `${baseUri}/external-service-error`
  } as const;
}

/**
 * Standard error response creators for common scenarios, namespaced under `baseUri`.
 */
export function createStandardErrors(baseUri: string) {
  const ErrorTypes = createErrorTypes(baseUri);

  return {
    emailRequired(instance: string): Response {
      return createProblemResponse({
        type: ErrorTypes.EMAIL_REQUIRED,
        title: 'Email Required',
        status: 400,
        detail: 'Email address is required for this operation',
        instance
      });
    },

    invalidEmail(instance: string, email?: string): Response {
      return createProblemResponse({
        type: ErrorTypes.INVALID_EMAIL,
        title: 'Invalid Email Format',
        status: 400,
        detail: email
          ? `The email address '${email}' is not in a valid format`
          : 'The provided email address is not in a valid format',
        instance
      });
    },

    userNotFound(instance: string, email?: string): Response {
      return createProblemResponse({
        type: ErrorTypes.USER_NOT_FOUND,
        title: 'User Not Found',
        status: 404,
        detail: email
          ? `No user found with email address '${email}'`
          : 'The requested user could not be found',
        instance
      });
    },

    challengeNotFound(instance: string): Response {
      return createProblemResponse({
        type: ErrorTypes.CHALLENGE_NOT_FOUND,
        title: 'Challenge Not Found',
        status: 400,
        detail: 'The authentication challenge was not found or has expired',
        instance
      });
    },

    authServiceUnavailable(instance: string): Response {
      return createProblemResponse({
        type: ErrorTypes.AUTH_SERVICE_ERROR,
        title: 'Authentication Service Unavailable',
        status: 503,
        detail: 'The authentication service is temporarily unavailable',
        instance
      });
    },

    internalServerError(instance: string, isDevelopment = false): Response {
      return createProblemResponse({
        type: ErrorTypes.INTERNAL_SERVER_ERROR,
        title: 'Internal Server Error',
        status: 500,
        detail: isDevelopment
          ? 'An internal server error occurred. Check server logs for details.'
          : 'An unexpected error occurred. Please try again later.',
        instance
      });
    },

    unauthorized(instance: string, detail = 'Authentication required'): Response {
      return createProblemResponse({
        type: ErrorTypes.UNAUTHORIZED,
        title: 'Unauthorized',
        status: 401,
        detail,
        instance
      });
    },

    forbidden(instance: string, detail = 'Access denied'): Response {
      return createProblemResponse({
        type: ErrorTypes.FORBIDDEN,
        title: 'Forbidden',
        status: 403,
        detail,
        instance
      });
    }
  };
}
