#!/bin/bash

# View Lighthouse Report
# Converts JSON report to HTML and opens in browser
# Usage: ./scripts/view-lighthouse-report.sh

REPORT_JSON="./lighthouse-reports/json/home.json"
REPORT_HTML="./lighthouse-reports/home.html"

if [ ! -f "$REPORT_JSON" ]; then
  echo "❌ Report not found: $REPORT_JSON"
  echo "Run ./scripts/run-lighthouse-audit.sh first"
  exit 1
fi

echo "📊 Generating HTML report from JSON..."

# Use Python to generate HTML with embedded JSON
python3 << 'PYTHON_EOF'
import json

with open('./lighthouse-reports/json/home.json', 'r') as f:
    data = json.load(f)

# Convert to JSON string for embedding
json_str = json.dumps(data)

html = f'''<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Lighthouse Audit Report</title>
  <style>
    * {{ margin: 0; padding: 0; box-sizing: border-box; }}
    body {{
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      min-height: 100vh;
      padding: 20px;
    }}
    .container {{
      max-width: 1200px;
      margin: 0 auto;
      background: white;
      border-radius: 12px;
      box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
      overflow: hidden;
    }}
    .header {{
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      color: white;
      padding: 40px;
      text-align: center;
    }}
    .header h1 {{ font-size: 2.5em; margin-bottom: 10px; }}
    .content {{ padding: 40px; }}
    .score-grid {{
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
      gap: 20px;
      margin-bottom: 40px;
    }}
    .score-card {{
      background: #f8f9fa;
      border-radius: 8px;
      padding: 20px;
      text-align: center;
      border-left: 4px solid #667eea;
    }}
    .score-card h3 {{
      font-size: 0.9em;
      color: #666;
      margin-bottom: 10px;
      text-transform: uppercase;
    }}
    .score-value {{
      font-size: 3em;
      font-weight: bold;
      margin: 10px 0;
    }}
    .score-value.excellent {{ color: #0cce6b; }}
    .score-value.good {{ color: #ffa400; }}
    .score-value.poor {{ color: #ff4e42; }}
    .score-bar {{
      width: 100%;
      height: 8px;
      background: #e0e0e0;
      border-radius: 4px;
      overflow: hidden;
      margin-top: 10px;
    }}
    .score-bar-fill {{
      height: 100%;
      background: linear-gradient(90deg, #0cce6b, #ffa400, #ff4e42);
      background-size: 300% 100%;
    }}
    .section {{ margin-bottom: 40px; }}
    .section h2 {{
      font-size: 1.5em;
      margin-bottom: 20px;
      color: #333;
      border-bottom: 2px solid #667eea;
      padding-bottom: 10px;
    }}
    .audit-item {{
      background: #f8f9fa;
      border-radius: 8px;
      padding: 15px;
      margin-bottom: 10px;
      border-left: 4px solid #ddd;
    }}
    .audit-item.pass {{ border-left-color: #0cce6b; }}
    .audit-item.fail {{ border-left-color: #ff4e42; }}
    .audit-item.warning {{ border-left-color: #ffa400; }}
    .audit-title {{ font-weight: 600; margin-bottom: 5px; }}
    .audit-description {{ font-size: 0.9em; color: #666; }}
    .footer {{
      background: #f8f9fa;
      padding: 20px;
      text-align: center;
      color: #666;
      font-size: 0.9em;
    }}
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>🔦 Lighthouse Audit Report</h1>
      <p>Accessibility Assessment</p>
    </div>
    <div class="content">
      <div id="report-content"></div>
    </div>
    <div class="footer">
      <p>Generated by Lighthouse • <span id="timestamp"></span></p>
    </div>
  </div>

  <script>
    const data = {json_str};

    let html = '<div class="score-grid">';

    for (const [categoryKey, category] of Object.entries(data.categories)) {{
      const score = Math.round(category.score * 100);
      const scoreClass = score >= 90 ? 'excellent' : score >= 50 ? 'good' : 'poor';

      html += `
        <div class="score-card">
          <h3>${{category.title}}</h3>
          <div class="score-value ${{scoreClass}}">${{score}}</div>
          <div class="score-bar">
            <div class="score-bar-fill" style="width: ${{score}}%"></div>
          </div>
        </div>
      `;
    }}

    html += '</div>';

    if (data.audits) {{
      html += '<div class="section"><h2>Audit Details</h2>';

      for (const [auditKey, audit] of Object.entries(data.audits)) {{
        if (!audit.title) continue;

        const status = audit.score === 1 ? 'pass' : audit.score === 0 ? 'fail' : 'warning';
        const statusIcon = status === 'pass' ? '✅' : status === 'fail' ? '❌' : '⚠️';

        html += `
          <div class="audit-item ${{status}}">
            <div class="audit-title">${{statusIcon}} ${{audit.title}}</div>
            <div class="audit-description">${{audit.description || ''}}</div>
          </div>
        `;
      }}

      html += '</div>';
    }}

    document.getElementById('report-content').innerHTML = html;
    document.getElementById('timestamp').textContent = new Date(data.fetchTime).toLocaleString();
  </script>
</body>
</html>'''

with open('./lighthouse-reports/home.html', 'w') as f:
    f.write(html)

print("✅ HTML report generated")
PYTHON_EOF

if [ $? -eq 0 ]; then
  echo ""
  echo "Opening in browser..."

  # Open in default browser
  if command -v open &> /dev/null; then
    open "$REPORT_HTML"
  elif command -v xdg-open &> /dev/null; then
    xdg-open "$REPORT_HTML"
  else
    echo "Open this file manually: $REPORT_HTML"
  fi
else
  echo "❌ Failed to generate HTML report"
  exit 1
fi