name: Deploy Demo App

on:
  push:
    branches: [main]
    paths:
      - 'src/demo-app/**'
      - 'src/**'
      - '.github/workflows/deploy-demo.yml'
  workflow_dispatch:

env:
  NODE_VERSION: '18'
  PNPM_VERSION: '8.15.0'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build Demo App
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Install library dependencies
        run: pnpm install --frozen-lockfile

      - name: Build library
        run: pnpm run build

      - name: Install demo app dependencies
        run: |
          cd src/demo-app
          pnpm install

      - name: Build demo app
        run: |
          cd src/demo-app
          NODE_ENV=production pnpm run build
        env:
          BASE_PATH: '/flows-auth'

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: src/demo-app/build

  deploy:
    name: Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
